axis = plt.gca()
plt.subplot(311)
plt.ylabel('Lin Accel (g)')
plt.xticks(np.arange(0, 55, step=5))
plt.yticks(np.arange(0, 55, step=5))
plt.margins(0, 0)
plt.plot(TL, LA[0, :])
plt.xlabel('Time (ms)')

axis.set_ylim(0, 35)
axis.set_xlim(0, 50)
plt.show()
    # plt.subplot(312)
    # plt.ylabel('Rot Vel (rad/sec)')
    # plt.xticks(np.arange(0, 55, step=5))
    # plt.yticks(np.arange(0, 45, step=5))
    # # axis.set_ylim(0,40)
    # # axis.set_xlim(0,50)
    # plt.plot(TL, RV[0, :])
    # plt.show()
